--- ../Makefile	2016-08-24 13:16:14.472309542 +0530
+++ ./Makefile	2016-08-24 13:34:11.800261213 +0530
@@ -87,12 +87,12 @@
 OSNAME:=$(shell uname -s)
 
 ifeq ($(OSNAME),Linux)
-OPTON += -march=native -mtune=native
+#OPTON += -march=native -mtune=native
 endif
 ifeq ($(OSNAME),Darwin)
 # (adjust flags or comment out this section for older versions of XCode or OS X)
 # (-mmacosx-versin-min= requires at least that version of SDK be installed)
-OPTON += -march=native -mmacosx-version-min=10.10
+#OPTON += -march=native -mmacosx-version-min=10.10
 #http://stackoverflow.com/questions/9840207/how-to-use-avx-pclmulqdq-on-mac-os-x-lion/19342603#19342603
 CFLAGS += -Wa,-q
 endif
